#!/usr/bin/env bash

# -------------------------------------------------------------------------- #
# Copyright 2010-2019, OpenNebula Systems                                    #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

if [ -z "${TIMEZONE}" ]; then
    exit 0
fi

if ! timedatectl set-timezone "${TIMEZONE}" 2>/dev/null; then
    if [ -f "/usr/share/zoneinfo/${TIMEZONE}" ]; then
        ln -sf "/usr/share/zoneinfo/${TIMEZONE}" /etc/localtime
    else
        echo "ERROR: Invalid timezone '${TIMEZONE}'" >&2
        exit 1
    fi
fi
