#!/usr/bin/env bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2021, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

. /etc/one-context.d/loc-10-network.d/functions

ACTION="$1"
OS_ID=$(detect_os)

if [ -z "${ACTION}" ] ; then
    ACTION="configure"
fi

if [ -z "${CONTEXT_NETCFG_TYPE}" ] ; then
    case "${OS_ID}" in
        alpine)
            CONTEXT_NETCFG_TYPE='interfaces'
            ;;
        altlinux)
            CONTEXT_NETCFG_TYPE='networkd'
            ;;
        debian|ubuntu|devuan)
            CONTEXT_NETCFG_TYPE='interfaces'
            ;;
        fedora|centos|rhel|almalinux|ol|rocky)
            CONTEXT_NETCFG_TYPE='scripts'
            ;;
        opensuse*)
            CONTEXT_NETCFG_TYPE='scripts'
            ;;
        freebsd)
            CONTEXT_NETCFG_TYPE='bsd'
            ;;
        *)
            CONTEXT_NETCFG_TYPE='none'
            ;;
    esac
fi

if [ "${CONTEXT_NETCFG_TYPE}" != 'none' ] ; then
    _found_valid_netcfg='no'
    for _cfgtype in ${CONTEXT_NETCFG_TYPE} ; do
        if [ -e "/etc/one-context.d/loc-10-network.d/netcfg-${_cfgtype}" ] ; then
            . "/etc/one-context.d/loc-10-network.d/netcfg-${_cfgtype}"
        else
            echo "ERROR [!]: Requested network type is not implemented: ${_cfgtype}" >&2
            exit 1
        fi

        if is_network_supported ; then
            _found_valid_netcfg='yes'
            break
        fi
    done

    if [ "${_found_valid_netcfg}" = 'no' ] ; then
        echo "ERROR [!]: None of the requested network types is supported on: ${OS_ID}" >&2
        exit 1
    fi
else
    # any action is meaningless without functioning network type
    ACTION='none'
fi

case "$ACTION" in
    none)
        echo "INFO: Network will not be configured" >&2
        ;;
    configure)
        configure_network
        ;;
    reconfigure)
        configure_network
        reload_network
        ;;
    *)
        echo "ERROR [!]: Unknown ACTION: ${ACTION}" >&2
        exit 1
        ;;
esac

exit 0
