#!/usr/bin/env bash

ENV_FILE=/var/run/one-context/one_env
MOUNT_DIR=${MOUNT_DIR:-/mnt}
TOKENTXT=$(cat "${MOUNT_DIR}/token.txt")

if [ -n "$ONEGATE_TOKEN" ]; then
    TOKENTXT="$ONEGATE_TOKEN"
fi

umask 0377
echo "export TOKENTXT=\"$TOKENTXT\"" > $ENV_FILE
echo "export VMID=\"$VMID\"" >> $ENV_FILE
echo "export ONEGATE_ENDPOINT=\"$ONEGATE_ENDPOINT\"" >> $ENV_FILE

function export_rc_vars
{
  if [ -f $1 ] ; then
    ONE_VARS=$(cat $1 | egrep -e '^[a-zA-Z\-\_0-9]*=' | sed 's/=.*$//')

    . $1

    for v in $ONE_VARS; do
        echo "export $v=\"${!v}\"" >> $ENV_FILE
    done
  fi
}

export_rc_vars ${CONTEXT_FILE}

chown root:root $ENV_FILE
chmod 0400 $ENV_FILE

