#!/bin/bash

MOUNT_DIR=${MOUNT_DIR:-/mnt}
TMP_DIR=$(mktemp -d "/tmp/one-context.XXXXXX")
TMP_FILE="${TMP_DIR}/one-start-script"
START_SCRIPT_AVAILABLE=no

chmod 700 "${TMP_DIR}"

if [ -n "$START_SCRIPT_BASE64" ]; then
    echo -en "$START_SCRIPT_BASE64" | openssl enc -d -base64 -A > $TMP_FILE
    START_SCRIPT_AVAILABLE=yes
elif [ -n "$START_SCRIPT" ]; then
    echo -en "$START_SCRIPT" > $TMP_FILE
    START_SCRIPT_AVAILABLE=yes
fi

if [ "$START_SCRIPT_AVAILABLE" = "yes" ]; then
    cd $MOUNT_DIR
    chmod +x $TMP_FILE
    $TMP_FILE
fi

rm -rf "${TMP_DIR}"
