#!/bin/bash

MOUNT_DIR=${MOUNT_DIR:-/mnt}
EXEC_TMP_BASE=${EXEC_TMP_BASE:-/tmp}
TMP_DIR=$(mktemp -d "$EXEC_TMP_BASE/one-context.XXXXXX")

chmod 700 "${TMP_DIR}"

if [ -z "$INIT_SCRIPTS" ]; then
    if [ -f "$MOUNT_DIR/init.sh" ]; then
        INIT_SCRIPTS=init.sh
    fi
fi

cd $MOUNT_DIR

for f in $INIT_SCRIPTS; do
    cp "$f" "${TMP_DIR}/"
    chmod +x $TMP_DIR/$f
    $TMP_DIR/$f
done

rm -rf "${TMP_DIR}"
