#!/bin/bash

activate_swaps() {

    SWAP_DRIVES=$(blkid -t TYPE="swap" -o device)
    for SWAP in $SWAP_DRIVES ; do
        if [ -z "$(swapon -s | grep $SWAP)" ]; then
            swapon $SWAP
        fi
    done
    
}

activate_swaps

