#!/usr/bin/env bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2021, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# shellcheck disable=SC2155

#
# network module interface
#

is_network_supported()
{
    false
}

configure_network()
{
    echo "ERROR [!]: No 'configure_network' implementation for the network type: ${NETCFG_TYPE}" >&2
    exit 1
}

stop_network()
{
    echo "ERROR [!]: No 'stop_network' implementation for the network type: ${NETCFG_TYPE}" >&2
    exit 1
}

start_network()
{
    echo "ERROR [!]: No 'start_network' implementation for the network type: ${NETCFG_TYPE}" >&2
    exit 1
}

reload_network()
{
    echo "ERROR [!]: No 'reload_network' implementation for the network type: ${NETCFG_TYPE}" >&2
    exit 1
}

#
# generic shared functions
#

is_true()
(
    _value=$(eval echo "\$${1}" | \
        sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | \
        tr '[:upper:]' '[:lower:]')
    case "$_value" in
        1|true|yes|y)
            return 0
            ;;
    esac

    return 1
)

# return OS ID
detect_os()
(
    if [ -f /etc/os-release ] ; then
        ID=
        # shellcheck disable=SC1091
        . /etc/os-release
        echo "$ID" | tr '[:upper:]' '[:lower:]'
    else
        uname | tr '[:upper:]' '[:lower:]'
    fi
)

skip_interface()
{
    [ -z "${_DEV}" ] && return 0

    is_true "${_DHCP}" && return 1
    is_true "${_DHCP6}" && return 1

    [ -z "${_IP}${_IP6}" ] && return 0

    return 1
}

# args: <iface> <name>
get_iface_var()
(
    iface=$(echo "$1" | tr '[:lower:]' '[:upper:]')
    var_name="${iface}_${2}"
    eval "echo \"\${${var_name}}\""
)

# Gets IP address from a given MAC
mac2ip()
(
    mac="$1"

    ip_a=$(echo "$mac" | cut -d: -f 3)
    ip_b=$(echo "$mac" | cut -d: -f 4)
    ip_c=$(echo "$mac" | cut -d: -f 5)
    ip_d=$(echo "$mac" | cut -d: -f 6)

    echo "0x${ip_a}.0x${ip_b}.0x${ip_c}.0x${ip_d}"
)

mask2cidr()
(
    mask="$1"
    nbits=0
    IFS=.
    for dec in $mask ; do
        case "$dec" in
            255) nbits=$((nbits + 8)) ;;
            254) nbits=$((nbits + 7)) ; break ;;
            252) nbits=$((nbits + 6)) ; break ;;
            248) nbits=$((nbits + 5)) ; break ;;
            240) nbits=$((nbits + 4)) ; break ;;
            224) nbits=$((nbits + 3)) ; break ;;
            192) nbits=$((nbits + 2)) ; break ;;
            128) nbits=$((nbits + 1)) ; break ;;
            0) break ;;
            *) echo "Error: $dec is not recognised"; exit 1 ;;
        esac
    done
    echo "$nbits"
)

# Gets the network part of an IP
# arg: <iface>
get_network()
(
    network=$(get_iface_var "$1" "NETWORK")

    if [ -z "$network" ]; then
        ip=$(get_ip "$1")
        mask=$(get_mask "$1")
        network=$(awk -v ip="$ip" -v mask="$mask" 'END {
            split(ip, ip_b, "."); split(mask, mask_b, ".");
            for (i=1; i<=4; ++i) x = x "." and(ip_b[i], mask_b[i]);
            sub(/^./, "", x); print x; }' </dev/null)
    fi

    echo "$network"
)

# Gets the network mask
# arg: <iface>
get_mask()
(
    mask=$(get_iface_var "$1" "MASK")
    echo "${mask:-255.255.255.0}"
)

# Gets device MTU
# arg: <iface>
get_mtu()
(
    mtu=$(get_iface_var "$1" "MTU")
    echo "${mtu:-1500}"
)

# Gets the network gateway
# arg: <iface>
get_gateway()
(
    get_iface_var "$1" "GATEWAY"
)

# Gets the network gateway6
# arg: <iface>
get_gateway6()
(
    get_iface_var "$1" "GATEWAY6"
)

# arg: <iface>
get_ip()
(
    get_iface_var "$1" "IP"
)

# arg: <iface>
get_dns()
(
    get_iface_var "$1" "DNS"
)

# arg: <iface>
get_search_domain()
(
    get_iface_var "$1" "SEARCH_DOMAIN"
)

# arg: <iface>
get_interface_alias()
(
    env | sed -n "s#^\(${1}_ALIAS[0-9]\+\)_MAC=.*#\1#p" | sort
)

get_context_interfaces()
(
    env | sed -n 's/^\(ETH[0-9]\+\)_MAC=.*/\1/p' | sort
)

get_pci_interfaces()
(
    env | sed -n 's/^\(PCI[0-9]\+\)_MAC=.*/\1/p' | sort
)

get_interface_mac()
(
    ip link show | awk '/^[0-9]+: [A-Za-z0-9@]+:/ { device=$2; gsub(/:/, "",device); split(device,dev,"@")} /link\/ether/ { print dev[1]  " " $2 }'
)

get_dev()
(
    list="$1"
    mac="$2"

    echo "$list" | grep "$mac" | cut -d' ' -f1 | tail -n1
)

# arg: <interface/alias>
setup_ipadr_vars()
{
    export _IP=$(get_ip "$1")
    export _NETWORK=$(get_network "$1")
    export _MASK=$(get_mask "$1")
    export _CIDR=$(mask2cidr "$_MASK")
    export _DHCP=$(get_iface_var "$1" "DHCP")
}

# arg: <interface/alias>
setup_ip6adr_vars()
{
    export _IP6=$(get_iface_var "$1" "IP6")
    export _IP6_PREFIX_LENGTH=$(get_iface_var "$1" "IP6_PREFIX_LENGTH")
    export _IP6_ULA=$(get_iface_var "$1" "IP6_ULA")
    export _DHCP6=$(get_iface_var "$1" "DHCP6")

    [ -z "$_IP6" ] && _IP6=$(get_iface_var "$1" "IPV6")
    [ -z "$_IP6_PREFIX_LENGTH" ] && _IP6_PREFIX_LENGTH=64
}

# arg: <interface>
setup_iface_vars()
{
    _iface_mac=$(get_interface_mac)

    export _MAC=$(get_iface_var "$1" "MAC")
    export _DEV=$(get_dev "$_iface_mac" "$_MAC")
    export _MTU=$(get_mtu "$1")
    export _GATEWAY=$(get_gateway "$1")
    export _METRIC=$(get_iface_var "$1" "METRIC")
    export _DNS=$(get_dns "$1")
    export _SEARCH_DOMAIN=$(get_search_domain "$1")
    export _GATEWAY6=$(get_gateway6 "$1")

    setup_ipadr_vars "$1"
    setup_ip6adr_vars "$1"
}

# arg: <alias>
setup_alias_vars()
{
    export _EXTERNAL=$(get_iface_var "$1" "EXTERNAL")
    export _DETACH=$(get_iface_var "$1" "DETACH")
}

get_nameservers()
(
    _dns_variables=$(env | sed -n 's/^\(ETH[0-9]\+_DNS\)=.*/\1/p' | sort)

    for _dns in DNS ${_dns_variables} ; do
        _value=$(eval "echo \"\${$_dns}\"")
        if [ -n "$_value" ] ; then
            echo "$_value"
        fi
    done
)

get_searchdomains()
(
    _search_domains=$(env | sed -n 's/^\(ETH[0-9]\+_SEARCH_DOMAIN\)=.*/\1/p' | sort)

    for _search in SEARCH_DOMAIN ${_search_domains} ; do
        _value=$(eval "echo \"\${$_search}\"")
        if [ -n "$_value" ] ; then
            echo "$_value"
        fi
    done
)

gen_resolvconf()
{
    export _NAMESERVERS=$(get_nameservers)
    export _SEARCH_DOMAINS=$(get_searchdomains)

    [ -z "$_NAMESERVERS" ] && return 0

    if [ -L /etc/resolv.conf ]; then
        unlink /etc/resolv.conf
    else
        cat /dev/null > /etc/resolv.conf
    fi

    for _nameserver in $_NAMESERVERS ; do
        echo "nameserver ${_nameserver}" >> /etc/resolv.conf
    done

    if [ -f /etc/sysconfig/network/config ]; then
        sed -i "/^NETCONFIG_DNS_STATIC_SERVERS=/ s/=.*$/=\"${_NAMESERVERS}\"/" /etc/sysconfig/network/config
    fi

    [ -z "$_SEARCH_DOMAINS" ] && return 0

    echo "search ${_SEARCH_DOMAINS}" >> /etc/resolv.conf

    if [ -f /etc/sysconfig/network/config ]; then
        sed -i "/^NETCONFIG_DNS_STATIC_SEARCHLIST=/ s/=.*$/=\"${_SEARCH_DOMAINS}\"/" /etc/sysconfig/network/config
    fi
}
