#!/usr/bin/env bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2021, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# shellcheck disable=SC2155

#
# network module interface
#

is_network_supported()
{
    false
}

configure_network()
{
    echo "ERROR [!]: No 'configure_network' implementation for the network type: ${NETCFG_TYPE}" >&2
    exit 1
}

stop_network()
{
    echo "ERROR [!]: No 'stop_network' implementation for the network type: ${NETCFG_TYPE}" >&2
    exit 1
}

start_network()
{
    echo "ERROR [!]: No 'start_network' implementation for the network type: ${NETCFG_TYPE}" >&2
    exit 1
}

reload_network()
{
    echo "ERROR [!]: No 'reload_network' implementation for the network type: ${NETCFG_TYPE}" >&2
    exit 1
}

#
# generic shared functions
#

is_true()
(
    _value=$(eval echo "\$${1}" | \
        sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | \
        tr '[:upper:]' '[:lower:]')
    case "$_value" in
        1|true|yes|y)
            return 0
            ;;
    esac

    return 1
)

# return OS ID
detect_os()
(
    if [ -f /etc/os-release ] ; then
        ID=
        # shellcheck disable=SC1091
        . /etc/os-release
        echo "$ID" | tr '[:upper:]' '[:lower:]'
    else
        uname | tr '[:upper:]' '[:lower:]'
    fi
)

skip_interface()
{
    [ -z "${dev}" ] && return 0

    is_true "${dhcp}" && return 1
    is_true "${dhcp6}" && return 1

    [ -z "${ip}${ip6}" ] && return 0

    return 1
}

# args: <iface> <name>
get_iface_var()
(
    _iface=$(echo "$1" | tr '[:lower:]' '[:upper:]')
    _var_name="${_iface}_${2}"
    eval "echo \"\${${_var_name}}\""
)

# Gets IP address from a given MAC
mac2ip()
(
    _mac="$1"

    _ip_a=$(echo "$_mac" | cut -d: -f 3)
    _ip_b=$(echo "$_mac" | cut -d: -f 4)
    _ip_c=$(echo "$_mac" | cut -d: -f 5)
    _ip_d=$(echo "$_mac" | cut -d: -f 6)

    echo "0x${_ip_a}.0x${_ip_b}.0x${_ip_c}.0x${_ip_d}"
)

mask2cidr()
(
    _mask="$1"
    _nbits=0
    IFS=.
    for _dec in $_mask ; do
        case "$_dec" in
            255) _nbits=$((_nbits + 8)) ;;
            254) _nbits=$((_nbits + 7)) ; break ;;
            252) _nbits=$((_nbits + 6)) ; break ;;
            248) _nbits=$((_nbits + 5)) ; break ;;
            240) _nbits=$((_nbits + 4)) ; break ;;
            224) _nbits=$((_nbits + 3)) ; break ;;
            192) _nbits=$((_nbits + 2)) ; break ;;
            128) _nbits=$((_nbits + 1)) ; break ;;
            0) break ;;
            *) echo "Error: $_dec is not recognised"; exit 1 ;;
        esac
    done
    echo "$_nbits"
)

# Gets the network part of an IP
# arg: <iface>
get_network()
(
    _network=$(get_iface_var "$1" "NETWORK")

    if [ -z "$_network" ]; then
        _ip=$(get_ip "$1")
        _mask=$(get_mask "$1")
        _network=$(awk -v ip="$_ip" -v mask="$_mask" 'END {
            split(ip, ip_b, "."); split(mask, mask_b, ".");
            for (i=1; i<=4; ++i) x = x "." and(ip_b[i], mask_b[i]);
            sub(/^./, "", x); print x; }' </dev/null)
    fi

    echo "$_network"
)

# Gets the network mask
# arg: <iface>
get_mask()
(
    _mask=$(get_iface_var "$1" "MASK")
    echo "${_mask:-255.255.255.0}"
)

# Gets device MTU
# arg: <iface>
get_mtu()
(
    _mtu=$(get_iface_var "$1" "MTU")
    echo "${_mtu:-1500}"
)

# Gets the network gateway
# arg: <iface>
get_gateway()
(
    get_iface_var "$1" "GATEWAY"
)

# Gets the network gateway6
# arg: <iface>
get_gateway6()
(
    get_iface_var "$1" "GATEWAY6"
)

# arg: <iface>
get_ip()
(
    get_iface_var "$1" "IP"
)

# arg: <iface>
get_dns()
(
    get_iface_var "$1" "DNS"
)

# arg: <iface>
get_search_domain()
(
    get_iface_var "$1" "SEARCH_DOMAIN"
)

# arg: <iface>
get_interface_alias()
(
    # sed on freebsd does not recognize '+' - replacing with asterisk
    env | sed -n "s#^\(${1}_ALIAS[0-9][0-9]*\)_MAC=.*#\1#p" | sort
)

get_context_interfaces()
(
    # sed on freebsd does not recognize '+' - replacing with asterisk
    env | sed -n 's/^\(ETH[0-9][0-9]*\)_MAC=.*/\1/p' | sort
)

get_pci_interfaces()
(
    # sed on freebsd does not recognize '+' - replacing with asterisk
    env | sed -n 's/^\(PCI[0-9][0-9]*\)_MAC=.*/\1/p' | sort
)

get_interface_mac()
(
    ip link show | awk '/^[0-9]+: [A-Za-z0-9@]+:/ { device=$2; gsub(/:/, "",device); split(device,dev,"@")} /link\/ether/ { print dev[1]  " " $2 }'
)

get_dev()
(
    _list="$1"
    _mac="$2"

    echo "$_list" | grep "$_mac" | cut -d' ' -f1 | tail -n1
)

# arg: <interface/alias>
setup_ipadr_vars()
{
    export ip=$(get_ip "$1")
    export network=$(get_network "$1")
    export mask=$(get_mask "$1")
    export cidr=$(mask2cidr "$mask")
    export dhcp=$(get_iface_var "$1" "DHCP")
}

# arg: <interface/alias>
setup_ip6adr_vars()
{
    export ip6=$(get_iface_var "$1" "IP6")
    export ip6_prefix_length=$(get_iface_var "$1" "IP6_PREFIX_LENGTH")
    export ip6_ula=$(get_iface_var "$1" "IP6_ULA")
    export dhcp6=$(get_iface_var "$1" "DHCP6")

    [ -z "$ip6" ] && ip6=$(get_iface_var "$1" "IPV6")
    [ -z "$ip6_prefix_length" ] && ip6_prefix_length=64
}

# arg: <interface>
setup_iface_vars()
{
    _iface_mac=$(get_interface_mac)

    export mac=$(get_iface_var "$1" "MAC")
    export dev=$(get_dev "$_iface_mac" "$mac")
    export mtu=$(get_mtu "$1")
    export gateway=$(get_gateway "$1")
    export metric=$(get_iface_var "$1" "METRIC")
    export dns=$(get_dns "$1")
    export search_domains=$(get_search_domain "$1")
    export gateway6=$(get_gateway6 "$1")

    setup_ipadr_vars "$1"
    setup_ip6adr_vars "$1"
}

# arg: <alias>
setup_alias_vars()
{
    export external=$(get_iface_var "$1" "EXTERNAL")
    export detach=$(get_iface_var "$1" "DETACH")
}

get_nameservers()
(
    # sed on freebsd does not recognize '+' - replacing with asterisk
    _dns_variables=$(env | sed -n 's/^\(ETH[0-9][0-9]*_DNS\)=.*/\1/p' | sort)

    for _dns in DNS ${_dns_variables} ; do
        _value=$(eval "echo \"\${$_dns}\"")
        if [ -n "$_value" ] ; then
            echo "$_value"
        fi
    done
)

get_searchdomains()
(
    # sed on freebsd does not recognize '+' - replacing with asterisk
    _search_domains=$(env | sed -n 's/^\(ETH[0-9][0-9]*_SEARCH_DOMAIN\)=.*/\1/p' | sort)

    for _search in SEARCH_DOMAIN ${_search_domains} ; do
        _value=$(eval "echo \"\${$_search}\"")
        if [ -n "$_value" ] ; then
            echo "$_value"
        fi
    done
)

gen_resolvconf()
{
    export all_nameservers=$(get_nameservers)
    export all_search_domains=$(get_searchdomains)

    [ -z "$all_nameservers" ] && return 0

    if [ -L /etc/resolv.conf ]; then
        unlink /etc/resolv.conf
    else
        cat /dev/null > /etc/resolv.conf
    fi

    for _nameserver in $all_nameservers ; do
        echo "nameserver ${_nameserver}" >> /etc/resolv.conf
    done

    if [ -f /etc/sysconfig/network/config ]; then
        sed -i "/^NETCONFIG_DNS_STATIC_SERVERS=/ s/=.*$/=\"${all_nameservers}\"/" /etc/sysconfig/network/config
    fi

    [ -z "$all_search_domains" ] && return 0

    echo "search ${all_search_domains}" >> /etc/resolv.conf

    if [ -f /etc/sysconfig/network/config ]; then
        sed -i "/^NETCONFIG_DNS_STATIC_SEARCHLIST=/ s/=.*$/=\"${all_search_domains}\"/" /etc/sysconfig/network/config
    fi
}
